services:
  - type: web
    name: ngandus-media-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.3
      - key: DATABASE_URL
        fromDatabase:
          name: ngandus-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

databases:
  - name: ngandus-db
    databaseName: ngandus_media
    user: ngandus_user
